source("http://bioconductor.org/biocLite.R")
biocLite("BiocUpgrade")
setwd("C:/Users/superstudent/Desktop/emil/WSP/wsp")
getwd()

biocLite('stringr')
library(stringr)
biocLite('limma')
library(limma)
biocLite('GSA')
library(GSA)
biocLite('piano')
library(piano)
biocLite('openxlsx')
library(openxlsx)
biocLite('shiny')
library(shiny)
a<-5
b<-6
